### ISSUE TITLE
I'm insterested in your work! Could the compact respresentation produced by SP be uesd in Image Retrieval？

### ISSUE THREAD

**Issue by STSTERANDMOMO** [billpsomas/simpool#1]

**Comment by billpsomas** [comment]
Hello,

Yes of course you can use it for Image Retrieval. 

In Table C4 (supplementary), you will find some results on ROxford and RParis. These results are from our models without any fine-tuning (k-NN classification on extracted features). 

Don't hesitate to ask me anything more :)
